### PR TITLE
Fix turret plates on wrong team

### PR DESCRIPTION
**Pull request by arbolitoloco1**
I realised we have no patch in the game timeline, so the only fix i could think of was checking if we can get an event_dto for the turret plate or not.

If there is event_dto: 12.14 or earlier
If not: 12.15 or newer

I also added a test when merging to check that the number of turret kill events in the timeline matches the number of turrets destroyed in data.

I imagine this change in Riots timeline wasnt intended, as the teamId still belongs to the "owner" of the turret for turret kill events, but not for turret plate kill events. So maybe it'll change again in the future, who knows.

These are the vods for the test games I added:
ESPORTSTMNT03_2961931: https://www.youtube.com/watch?v=i34uceAGw0I (Post 12.15)
[ESPORTSTMNT01_3096461: https://www.youtube.com/watch?v=K2BZKorXGi4 (Pre 12.15)

### CODE REVIEW

**Comment by mrtolkien** [comment]
Looks good overall!

Could you add a small test to check that previous behaviour was unchanged? Validating the value of `LolGameTeamBuildingKill` for one game before 12.15 and for another after.

Thanks a lot for your help, once I've merged the PR I'll do some cleaning up on this repo too.

**Comment by arbolitoloco1** [comment]
Thank you! I don't understand how to validate `LoLGameTeamBuildingKill`, though, im kind of new in this programming world, sorry hahah

**Comment by mrtolkien** [comment]
Just write a test with one of the `.json` you added and verify that the resulting value is good!

Pretty much just call the function and check the return values.

**Comment by arbolitoloco1** [comment]
So... i made the checks with ESPORTSTMNT03_2961931 (the 12.16 game) checking the output using the bayes rofl, but there are some wrong things, for example
Screenshot 2022-09-16 172650
This image shows that the first turret plate for blue team was in mid lane, however both in the riot_transmute output and in bayes timeline it shows that both teams got their first turret plates in bot lane

Game timeline straight from bayes (first turret_plate events for each team):
Screenshot 2022-09-16 172717
Screenshot 2022-09-16 172733

The timestamp makes sense for both teams, but the lanes are completely wrong

**Comment by mrtolkien** [comment]
Please fix the merge conflicts so we can run the tests!

**Comment by arbolitoloco1** [comment]
> Please fix the merge conflicts so we can run the tests!

Fixed!

Regarding your question in the issue, in my opinion we should merge the pr so that it won't fail with games from 12.15 to 12.17

**Pull request closed without merging**
